spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:[forwardedPort]/${DB_DATABASE}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# SSH Tunnel Configuration
ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  private-key: ${SSH_PRIVATE_KEY}
  port: ${SSH_PORT}
  db-host: ${DB_HOST}
  db-port: ${DB_PORT}

crawling:
  chrome-browser-path:
