spring:
  config:
    activate:
      on-profile: local

# SSH Tunnel Configuration
ssh:
  host: ${SSH_HOST}
  user: ${SSH_USER}
  private-key: ${SSH_PRIVATE_KEY}
  port: ${SSH_PORT}
  db-host: ${DB_HOST}
  db-port: ${DB_PORT}
