spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: development
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Seoul

swagger:
  version: 0.0.1
  server-url: ${SERVER_URL:http://localhost:8080}
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    syntax-highlight:
      theme: none

auth:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET:secret}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

oauth:
  apple:
    client-id: ${APPLE_OAUTH_CLIENT_ID}
    redirect-uri: ${APPLE_OAUTH_REDIRECT_URI}
    team-id: ${APPLE_OAUTH_TEAM_ID}
    key-id: ${APPLE_OAUTH_KEY_ID}
    private-key-path: ${APPLE_OAUTH_PRIVATE_KEY_PATH} # TODO prod 환경 분리
    url:
      token-url: ${APPLE_OAUTH_TOKEN_URL}
      auth-url: ${APPLE_OAUTH_AUTH_URL}

  google:
    redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}
    client-id: ${GOOGLE_OAUTH_CLIENT_ID}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    scope: ${GOOGLE_OAUTH_SCOPE}
    url:
      authorization-uri: ${GOOGLE_AUTHORIZATION_URL}
      token-uri: ${GOOGLE_OAUTH_TOKEN_URI}
      user-info-url: ${GOOGLE_OAUTH_USER_INFO_URL}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    url:
      auth-code-url: https://kauth.kakao.com/oauth/authorize
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me

aws:
  region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${BUCKET_NAME}
    env: ${BUCKET_ENV}
    base-image: ${BASE_KEY}

security:
  rate-limit:
    max-requests: 100 # 시간 윈도우당 최대 요청 수
    window-seconds: 1 # 시간 윈도우(초)

logging:
  config: classpath:logback-spring.xml
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

expo:
  url:
    send-notification: https://exp.host/--/api/v2/push/send
    get-receipts: https://exp.host/--/api/v2/push/getReceipts
