name: CI test run workflow

on:
  pull_request:
    branches: [ 'main', 'develop' ]
  push:
    branches:
      - 'feat/2-ci-automation'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test/
