name: CI test run workflow

on:
  pull_request:
    branches: [ 'main', 'develop' ]
  
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create .env file
        run: |
          echo "${{ secrets.CI_ENV_FILE }}" > .env


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 테스트결과_페이지
          path: build/reports/tests/test/
