name: PR Size Labeler

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count Lines
        id: count
        run: |
          git fetch origin ${{ github.base_ref }}
          # Get the PR's head commit
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          # Calculate total changes in PR
          CHANGED_LINES=$(git diff --stat origin/${{ github.base_ref }}..pr-branch | tail -n 1 | cut -d' ' -f4)
          echo "changed_lines=$CHANGED_LINES" >> $GITHUB_OUTPUT


      - name: Add size label
        uses: actions/github-script@v7
        with:
          script: |
            const changedLines = parseInt(process.env.CHANGED_LINES);
            let sizeLabel = '';
            
            if (changedLines >= 1000) {
              sizeLabel = 'size/XXL';
            } else if (changedLines >= 500) {
              sizeLabel = 'size/XL';
            } else if (changedLines >= 100) {
              sizeLabel = 'size/L';
            } else if (changedLines >= 30) {
              sizeLabel = 'size/M';
            } else if (changedLines >= 10) {
              sizeLabel = 'size/S';
            } else {
              sizeLabel = 'size/XS';
            }
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [sizeLabel]
            });
        env:
          CHANGED_LINES: ${{ steps.count.outputs.changed_lines }}
